version: '3'

volumes:
  postgres-data:

services:
  web:
    container_name: "web"
    build: ./shop_organick/
    volumes:
      - ./shop_organick:/code:delegated,rw
    ports:
      - "80:8000"
    env_file: "./env_docker"
    depends_on:
      - db

  db:
    container_name: "db"
    image: postgres:14
    env_file: "./env_docker"
    volumes:
      - postgres-data:/var/lib/postgresql/data